### ISSUE TITLE
Documentation for developers

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#103]
Again I would like to touch this topic and ask where we should store information for developers? This is still an issue because many people ask how to set it up and try it. Questions are regarding both qt4 and web versions, so maybe we could store this documentation under mxcube git page?
I see that there is documentation about web version on mxcube3 wiki and there is some info under doc that needs to be build with sphinx. Should we keep them both?

What do you think?

**Comment by meguiraun** [comment]
hi all,

They idea we had is to leave the wiki for docs in form of howto-s, guidelines, code recipes, etc. For documenting the code itself, I think gh-pages is quite useful (although we have not use it extensively yet, and only for web stuff, http://mxcube.github.io/mxcube3/). 

I think we should only have a single access point for all the code documentation (qt, web, hardwareobjects...), but I do not know where is the best place. Perhaps putting all the generated sphinx files somewhere in the gh-pages of the main mxcube repo? And just add a link in the main mxcube page (the one created by matias) `http://mxcube.github.io/mxcube/doc/index.html`

**Comment by xenocs** [comment]
If I can contribute to the discussion I rather like the idea of a documentation that is part of the project so that is distributed together with it and that the history of the documentation is the same as the git history of the project itself.   I am talking about the developers documentation (other than the code documentation itself):  howtos, guidelines, release notes, code snippets, etc... In this way the installed documentation would correspond to the installed source.

I see that there is already a doc/ directory in the project that contains more or less the same info as the wiki.  I would rather vote to promote the use of the doc/ directory for documentation rather than the wiki

**Comment by vrey01** [comment]
If I can contribute to the discussion I rather like the idea of a documentation that is part of the project so that is distributed together with it and that the history of the documentation is the same as the git history of the project itself.   I am talking about the developers documentation (other than the code documentation itself):  howtos, guidelines, release notes, code snippets, etc... In this way the installed documentation would correspond to the installed source.

I see that there is already a doc/ directory in the project that contains more or less the same info as the wiki.  I would rather vote to promote the use of the doc/ directory for documentation rather than the wiki

**Comment by IvarsKarpics** [comment]
Hi,
Then we have three places: doc directory in git code, wiki and gh-pages. From my point of view, documentation build with sphinx from doc directory is a good place, because it comes along the code and has a git history. It is fine that there are different places, the main thing is that we have some documentation. For example, I got many questions about hardware objects (how they are organized) and how to install and run web version. I will gather some documentation and put in doc directory about general infrastructure. Could somebody put in wiki, gh-pages a manual how to install web version? I know that Matias had a nice setup manual. Then If someone would ask me about this manual I could just send the link.

**Comment by mguijarr** [comment]
Daniele proposed himself to add the MXCuBE manual in the original ppt format, to let people changing it as necessary. It will go under the  "doc" directory I guess. I will add a link to it in the MXCuBE web page too.
@IvarsKarpics : thanks a lot for your documentation effort - hopefully we will contribute at some point
@IvarsKarpics : about the setup manual, are you talking about [this](http://forge.epn-campus.eu/projects/mxcube/wiki/New_v2_branch) ? We may have a better, more up-to-date version but I can't find it...

**Comment by IvarsKarpics** [comment]
Hi,
Powerpoint is fine, but I presume it would be difficult to maintain. Also then everything is in one place and comes together when cloned from git. I started to write manual with sphinx, because we do not have it and it was requested by users. I am taking ppt manual as a basis, When the first mature version will come then I will inform others to have a look and give some feedback. 
My idea was two have two manuals: one for qt and other for web, because the way how to start app and general layout will differ. 
@mguijarr : no. I was thinking about the manual how to run web app. I will find that email and copy information in doc.

**Comment by IvarsKarpics** [comment]
@mguijarr : In the issue https://github.com/mxcube/mxcube3/issues/34 you had few lines how to run code with webpack. For me they worked. Should I add this to instruction manual and give to other people if they ask?

**Comment by meguiraun** [comment]
hi,
The issue mxcube/mxcube3#34 only refers to running the web interface, e.g. the python server is missing as well as the installation of the python requirements. Which is fine if people only want to try the interface.
I will create a wiki page for the v3 will the info needed for installing&running the server (basically copy&update what Matias&Bixente did a while ago).

**Comment by IvarsKarpics** [comment]
Ok, good. Then I will copy/paste it to docs.

**Comment by meguiraun** [comment]
Have a look at the [wiki](https://github.com/mxcube/mxcube3/wiki/How-to:-Installation)

The basic steps are explained, for installing the dependencies as well as launching the server and the client (in devel mode, but very useful for demos).

**Comment by IvarsKarpics** [comment]
Thanks! I added it also to docs. I dont know how realistic is to keep documentation in several places, but lets try.
I was thinking to update main README file. It could have just a short information about mxcube, link to http://mxcube.github.io/mxcube/ and two links how to install and run:
https://github.com/mxcube/mxcube/blob/master/docs/source/installation_instructions_qt4.rst
https://github.com/mxcube/mxcube/blob/master/docs/source/installation_instructions_web.rst

second link could be also link to your given wiki page.

**Comment by mguijarr** [comment]
Happy to see some progress on all this :)
:+1: for updating README file
We should probably make a README for MXCuBE 3 too

**Comment by IvarsKarpics** [comment]
- Manual added to docs
- Updated README file.
- More documentation about API and Qt version in docs
- Information about mxcube3 available in wiki
  Keep the literature spirit alive!

I will close this issue, but we can open it at any time if there is a need to discuss this.
