### ISSUE TITLE
Rename HardwareObjects.xml to example_xmls

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#114]
Rename also keyword argument --hardwareRepository to something like --configDir

**Comment by mguijarr** [comment]
This would be to 2.3 ? We need to make a roadmap for 2.3.

Those kind of parameters come from the ESRF old Bliss Framework legacy (code from 2003...). We should probably study the possibility of modernizing this aspect of MXCuBE. We do not need a framework any more, but which direction to take ? Either going through some new multi-purpose
beamline control library like the new Bliss project at ESRF or to some really specific application-oriented code, just for MXCuBE.

**Comment by IvarsKarpics** [comment]
This is a brainstorming ideas during the developers workshop.
No clear decisions or something else. In general these are major changes that need a common decision. I dont have an answer now, but we can keep the ball rolling and discuss this.

**Comment by paulau** [comment]
Dear all, 
My first stuck by first look at  mxcube was .gui file. I was thinking what software must process these file types? Then I realized, that it should be GUIBuilder of Blissframework. So, one must forget Qt4Designer and get used to work with GUIBuilder. (I did not managed to start new project with GUIBuilder, though I used around 1-3 Years old version of Blisframework). First impression was that one needs to use standard software like Qt4Designer, rather than to develop own GUI IDE Blissframework GUIBuilder-Supervisor etc. Instead better to focus on part related to accelerator. But I may be wrong.  May be understanding of all advantages of use of Blissframework will come later. 
Greetings, 
Pavel

**Comment by marcus-oscarsson** [comment]
Hi again :)

So it seems like the old .gui file is outdated and that it have been replaced bu the yml file as Ivars mentioned in #198. I don't have an answer that help you much in your work but I can give you some
historical context. 

The BlissFramework was originally developed at ESRF for Python and Qt3, @mguijarr and @beteva are the original authors. The problem at the time was that it was difficult to extend the Qt3 designer with python widgets. The BlissFramework also added some concepts that where specific to beamline control. It was at the time a very useful and flexible tool. It would have been complicated to achieve the same within the Qt3 Designer.

You are in a way right that it makes less sense to implement that kind of custom UI designer today with the current versions of Qt. I think it was simply done to be able to reuse some of the concepts in BlissFramework and maybe keep some level of backward compability.

We are currently looking at refactoring the core of MXCuBE, one consequence of that will probably be that BlissFramework will disappear. Actually the UI part of BlissFramework is not at all used in the MXCubE3 application and we are discussing ways on how to improve the HardwareObjects.

Cheers,
Marcus

**Comment by paulau** [comment]
Dear Marcus and all, 

I think several people (at least mguijarr and you) of community of mxcube developers expressed already idea "that  BlissFramework will disappear". My vote is presumably to support this initiative! In principle ui format of Qt Designer is also human readable. It could have sin to replace the whole Bliss Framework just by one ui file and reference that it is processed via QtDesigner. 

Greetings, 
Pavel

**Comment by paulau** [comment]
Hi Marcus,

Thanks, for reply.
I would compare software with my room. If I do not clean the room every
weekend, then it will be mess after two weeks!
The same in Software. It would be good to remove not used things from the
working version and bury them in the version
control system.

Also: I have impression, that to make a new project from the scratch is
easier, than to "re-factor" the old project.
Also: I am not sure, that I will be able to join the meeting on 7 of June.
Sorry. Greetings to all.

Greetings,
Pavel


2018-02-08 8:41 GMT+01:00 Marcus Oscarsson <notifications@github.com>:

**Comment by marcus-oscarsson** [comment]
Hi Pavel,

Hm, this issue was closed sometime ago so its probably better if we take this discussion in a more active issue. 

In anyways, I think we all somehow in one way or another can relate to your room analogy. Exactly how to proceed with the re-factoring is something that needs to be discussed in the developers meeting and we have not started on that topic yet. 

I'm personally looking forward to start with that after we have finished the work on the UI-API. We will have to wait and see how exactly the refactoring/redesign (in lack for better words) will be done ...

Cheers !
Marcus
