### ISSUE TITLE
Possible to collect inverse beam at discrete points along vector?

### ISSUE THREAD

**Issue by jlmuir** [mxcube/mxcubeqt#121]
Does MXCuBE support defining a vector and collecting in inverse beam mode at discrete points along that vector?

For example, is it possible to define a vector (e.g. define two graphical object points) in the crystal view and tell MXCuBE to collect, in inverse beam mode, 100 degrees total, with wedges of 20 degrees such that it would distribute 5 points equally along the vector (i.e. beginning and end and 3 in between), and collect 20 degree wedges at each of the points?

**Comment by IvarsKarpics** [comment]
Hi,

No, this feature is not available now in MXCuBE. However it would not be very difficult to implement it, because bits to do this exist. There could be two scenarios:
- After defining the vector extract necessary collection points and create individual collections. User creates a collection vector (helical line) between two points, enters the amount of necessary points and with a button click all centering points are created;
- Create a single collection and execute it as an inverse beam collection. This solution requires some queue manipulations.

In practice first solution might be easier to understand from users view.

**Comment by jlmuir** [comment]
OK, thanks for the info!
