### ISSUE TITLE
Possible to collect in fully automated mode?

### ISSUE THREAD

**Issue by jlmuir** [mxcube/mxcubeqt#126]
Does MXCuBE support a fully automated (i.e. unattended) data collection mode?  I think the answer is no, but I want to be sure I'm not missing something.

A fully automated mode would allow me to add a number of samples from automounter dewar positions to a queue and then run the queue to collect the data automatically.  I would be able to specify how each sample is collected by specifying a recipe.  The same recipe can be used by multiple samples.  I can override parts of a recipe on a per-sample basis.  The automatic collection mode would mount each sample, optically loop center, diffraction center (a.k.a. mesh center), and collect the dataset.

I know there's the MASSIF-1 beamline at the ESRF that uses the Passerelle workflow engine (see [Fully automatic characterization and data collection from crystals of biological macromolecules](http://journals.iucr.org/d/issues/2015/08/00/wa5095/index.html)), but is there support for it in MXCuBE, or is that a local patch to MXCuBE that the MASSIF-1 beamline developers carry?  (If I understand correctly, though, the support would be minimal anyway since the automated process would be triggered with a button press or something in MXCuBE that calls out to Passerelle, but from then on Passerelle _controls_ MXCuBE.)

**Comment by mguijarr** [comment]
In fact MXCuBE supports an unattended mode natively (called **pipeline data collection**), but it
is quite limited:
- you set centering mode to 'Fully automatic'
- you check/select samples in the tree, and you assign data collections to them (for example, Characterisation)
- you start the queue: MXCuBE will load the first sample, do an automatic centring, perform the data collection ; if centring fails, in fully automatic mode it just goes to the next sample. In case of characterisation, if it is successful the resulting strategy data collection is added automatically and it will also be executed.

This is rather simple - using the embedded XML-RPC server within MXCuBE allows to have a much finer control of the MXCuBE queue, so the "workflow" approach is better for more complicated use cases.

**Comment by jlmuir** [comment]
Thank you for letting me know; I really appreciate it!

For the pipeline data collection:
1. Can I save the queue to a file and load it again after restarting MXCuBE?
2. Can I save the data collections assigned to a sample in the queue as a file and then attach them to samples in the queue?  This is the _recipe_ concept I mentioned initially where I could have a standard set of data collections (i.e. a recipe) that I use for many samples and would want a way to easily attach them to samples in the queue.
3. Is it possible to assign a name and username (essentially name-value pairs with string values) to a puck?  Or maybe ISPyB supports this?
4. Is there macro support for the queue and data collections?  For example, I'd be interested in being able to use macros in file paths for where data is saved to disk (e.g. Standard Collection > Data location > Folder) like the following: `%d` expands to the dewar number of the mounted sample, `%m` expands to the name of the magazine (a.k.a. puck) of the mounted sample, `%u` expands to the username of the magazine of the mounted sample, and `%p` expands to the position in the magazine of the mounted sample.  This would enable me to use paths like `/data/mailin/%u/20160823/%m/%p` and not need to change them.
5. Will it do a mesh scan over the loop region at the current Phi angle and at +90 degrees away to determine the best place to shoot the crystal (and move to it)?  (If this would be done in the Advanced tab as a data collection attached to a sample, I'm sorry, it's disabled in my MXCuBE simulation, so I can't easily try it out.)

**Comment by IvarsKarpics** [comment]
Hi @jlmuir 

You mentioned points that circumnavigates around the mxcube meetings already for some years. I can try to answer this from the Qt4 gui point of view. Maybe Matias or someone from MaxIV can comment how its done in web version. So:
1. No. It is not possible right now. However there are serialization methods for main classes and with some effort it would be possible.
2. Also no. If the first is solved then it would be difficult to create a recipe concept.
**update** see #130 
3. Yes, you can assign a name to the puck in ISPyB, but it does not appear in mxcube, because there is no soap webservice that could provide info about pucks. For sure this should be added in ispyb. My feeling is that this should be as a RESTful service and in general we should use REST. But this is maybe a question for the next meeting in January.
4. Also not available, but it is a very nice idea! I will open an issue for this and will try to implement it, because I got a similar request also before.
**update** : see #127  and #128  for the implementation
5. You mean an Xray-centring? It involves a mesh scan, moving to best position, rotate 90, do a helical line along the goniometer axis and move to the best position. At our case it is mxcube that does all these steps. Why it is disabled? Did you checkout the master branch?

**Comment by pkeller** [comment]
Hi Lewis,

I agree with Matias about using the XML-RPC server for more complicated procedures. You can provide your own external "director" to implement your recipes, which can be Passerelle workflows but doesn't have to be. It is simple to do drive MXCuBE from Python in this way. In Java it should also be doable using [Apache XML-RPC](https://ws.apache.org/xmlrpc/xmlrpc2/), which I have looked at but never tried to connect to MXCuBE.

It might be that the queue model that is used by the XML-RPC server doesn't contain everything that you need, but I think that it is pretty complete by now and adding any missing bits shouldn't be hard.

**Comment by jlmuir** [comment]
@IvarsKarpics:

Wow!  That was fast.  Thank you for implementing those!

A few more comments on your comments:

> 2. Also no. If the first is solved then it would be difficult to create a recipe concept.

Why would it be difficult to create a recipe concept?  If you created a recipe which could be serialized to a file, then you could reference just the file path of the recipe on a sample in the queue.  Serializing the queue in question 1 would just serialize the path to the recipe file.  You could change the contents of the recipe file at will.  The recipe could then be read from the file (i.e. deserialized) at the time the sample is actually collected in the queue.

> 3. Yes, you can assign a name to the puck in ISPyB, but it does not appear in mxcube, because there is no soap webservice that could provide info about pucks.

OK, thanks.  Sorry to be asking about ISPyB here, but what about the second part to question 3 of having a _username_ assigned to a puck?  Does ISPyB support that?  Note that this would not necessarily be the username of the user collecting data with MXCuBE.  Another name for username might be owner, but regardless, I'm ultimately interested in having a computer account _username_ associated with the sample.  The idea is to facilitate our mail-in mode of data collection where we collect data for multiple organizations by intermingling pucks in the automounter dewar (kind of like time-shared batch processing in computing).  We use the username of the puck to write to a specific file system location for the user who owns the puck, hence the `%u` macro suggestion in question 4.

Or, if ISPyB doesn't have the notion of a username associated with a puck, and if it would be simpler or more useful, what about the concept of assigning arbitrary metadata to a puck in the form of string-valued key-value pairs?  Again, maybe ISPyB already has this?  The key could be something like `owner_username`.  Of course, this may be a classic example of needing to decide when something should have first-class status in the ISPyB database schema vs. a generic kind of solution like this.

> 5. You mean an Xray-centring?

Yes.

> It involves a mesh scan, moving to best position, rotate 90, do a helical line along the goniometer axis and move to the best position. At our case it is mxcube that does all these steps.

OK, great!  So this is what is in the Advanced tab?  And I could attach this advanced data collection to a sample in the queue before a standard collection, and end up with an automatically collected dataset for a sample that had been optically loop centered, X-ray centered, and then collected?

> Why it is disabled? Did you checkout the master branch?

It's been a while since I last checked out the master branch.  I can try again and see.

**Comment by jlmuir** [comment]
@mguijarr and @pkeller:

Thank you for your comments!  I really appreciate it!

I don't doubt your intuition, but it would be a big help to me to understand why you think the external workflow approach is better for fully automated data collection.  I'm not against the approach; in fact I think it has great value!  However, I'm wondering, why do you think it wouldn't be worthwhile to add more capabilities to the existing _pipeline data collection_ directly in MXCuBE?

It seems like support directly in MXCuBE for more capabilities in the _pipeline data collection_ would benefit people who don't want to implement a full external workflow approach.

I'm also thinking that for each new external workflow implementation, some kind of similar GUI will need to be created to enable setting up the _batch job_, if you will.  But maybe that's where the rub is: even though there might be similarities, there's not an easy way to create a reusable GUI?

Or maybe the external workflow approach is more desirable because it would work regardless of whether the beamline is using MXCuBE 2 or 3, whereas extending the _pipeline data collection_ would involve duplicate development effort for both MXCuBE 2 and 3?

I suspect I'm missing something philosophical, practical, or both about this; what am I missing here?  Thanks!

**Comment by pkeller** [comment]
Hi @jlmuir, I hope I wasn't sounding too dogmatic about this, I think that you have correctly identified that there are philosophical questions here. From Global Phasing's point of view, we are always interested in transferability (including to non-MXCuBE systems), and from that perspective we tend to think of beamline control systems as basic data collection servers that don't contain too much scientific logic.

The feature of the external "director" approach that I had in mind is the fact that the server-side part of it can be easily enabled or disabled at particular MXCuBE installations: select the modules that contain the required XML-RPC modules that offer the required methods (or write new ones if necessary), and ensure those modules are loaded (or not) by specifying them in (or omitting them from) the MXCuBE XML configuration file. This means that sites that don't need to get particular functionality to work can simply ignore it when setting up MXCuBE.

You are quite right that such an external process may well need a custom UI. This leads to the next question: where to put it and what should it look like? From the visitor perspective, I think that it is best to put it inside the existing MXCuBE GUIs rather than have a separate UI (skipping over a lot of argument and controversy from non-MXCuBE contexts here :-) ) and then you will need both a v2 and v3 GUI to enable the process to be offered in any MXCuBE deployment.

OTOH, for a procedure that is local to a single beamline or synchrotron and that is only carried out by beamline staff rather than visitors, this may be less important. For a UI that isn't offered inside the MXCuBE GUI, any UI framework could be used to set up and start the process, right down to CLI or script-based approaches. (In fact, a while ago, I prototyped exactly this with basic Python scripts, and found it pretty straightforward.) As you say, this will work for both versions of MXCuBE, and can be made easy to invoke in batch mode. The GUI will still show passively what is going on. Something that turns out to be generally useful can always have MXCuBE GUIs developed later, after the initial development has been done.

The best approach depends on circumstances of course, and if most of what you need already exists in MXCuBE then it may well be best to simply add to that.
