### ISSUE TITLE
MXCuBE license?

### ISSUE THREAD

**Issue by jlmuir** [mxcube/mxcubeqt#131]
Does MXCuBE have a default license?  A number of files in the `Bricks` directory contain GPL 3 terms, but I couldn't find an official statement on this (e.g. in a `LICENSE` file).  Thanks!

**Comment by IvarsKarpics** [comment]
The default licence is GPL3 (correct me if I am wrong). I created a PR #132 with a COPYING license file to make it more clear. We can rename to LICENSE if there is a need.
When rewrote all bricks to Qt4 I added this GPL3 header to files, because within the code there was no information about the license. I would suggest to add it also to hardware objects.

**Comment by jlmuir** [comment]
OK, thanks!
