### ISSUE TITLE
Does MXCuBE have unit tests?

### ISSUE THREAD

**Issue by jlmuir** [mxcube/mxcubeqt#134]
Does MXCuBE (or any subproject) have unit tests?

**Comment by IvarsKarpics** [comment]
Hi Lewis,

No, right now there are no unit tests available. Its not so easy to write a unit test, because MXCuBE is very user oriented. If it contained more algorithms and functions then it would be possible to use some test suites. However, each software should contain unit tests to improve the stability, repeatability etc. One option would be to use unittest module and add all hardware objects via BeamlineSetup. Then for each hardware object prepare a test suite (get value, get state).
What unit tests without a user interaction could test?

**Comment by jlmuir** [comment]
On 09/01, Ivars Karpics wrote:

> No, right now there are no unit tests available. Its not so easy to write a unit test, because MXCuBE is very user oriented. If it contained more algorithms and functions then it would be possible to use some test suites. However, each software should contain unit tests to improve the stability, repeatability etc. One option would be to use unittest module and add all hardware objects via BeamlineSetup. Then for each hardware object prepare a test suite (get value, get state).

Hi, Ivars!

Thanks for your answer.

> What unit tests without a user interaction could test? 

Well, I'm still quite limited in my understanding of how MXCuBE works, so I was really just asking in general.  I think things in MXCuBE that are not directly part of the GUI could be tested, and I think that would have value.  So, for example, if pressing a GUI button results in a call to a function that might be worth testing, a unit test that tests that function would be useful.

I can easily see value in testing hardware objects.  For example, if there's a motor hardware object, just testing things like moves, stops, running into limits, encoder readback, etc. would be useful.  For the case of a hardware object that speaks a particular communication protocol with a device via a TCP socket, for example, I think there's value in having a software device emulator that emulates the actual device.  (The emulator could be written in many ways, but one is just a TCP server written in Python or whatever.)  Then there's obvious value in testing the hardware object against the emulator to ensure it communicates correctly.  Having an emulator also provides the useful feature of being able to produce all kinds of error conditions which then enables testing the hardware object to ensure it handles those correctly.

On the topic of actual GUI testing, I'm less certain.  I know there used to be commercial products available for that, but I haven't looked into them in a long time.  I certainly don't like anything that does stuff like recording a mouse click at a certain screen position or something since that's horribly fragile.  On the other hand, iOS has some stuff for programmatic GUI automation which lets you programmatically generate UI events.  So, for example, you can get a reference to a button and trigger a tap event on it.  If there's something like this for Qt that is not fragile (e.g. there's a nice way to get a reference to UI controls), then maybe it would be worth considering.  But, I don't have a lot of experience doing this, so I can't say firsthand that I think it's really beneficial.  To date, my approach has been to try to keep the GUI as dumb as possible, and essentially try for an application model design where my GUI is really just a view for an application model.  I can then interact with my application model programmatically for testing and not require a graphical context for the GUI; in this design, I don't test GUI controls.

**Comment by IvarsKarpics** [comment]
Hi @jlmuir 

Coming back to the testing question...
I agree that GUI testing with writing massive code is not the best idea. Now mxcube has two different gui platforms and single code that will test both of them is not possible. I think it would be possible to write unittest for hardware level and this could be completely independent from gui. However, it will not possible to test all hardware objects because there are some Qt dependecies within them (you can not use Qt objects without creating QApplication). For example, Qt4_LimaVideo is used by Qt4_GraphicsManager, that is part of BeamlineSetup, AbstractCollect, etc. On the last PR #137  it tried to offer two solutions:
1. A jupyter notebook loads example hardware repository. You can load any hardware object, see methods, variables, etc. This could be useful to learn better the HardwareRepository
2. A mxcube_unittest.py with some tests. Here we could put all tests cases to test mxcube. For example, now it checks some get\* methods.

Maybe this helps to start rolling this testing question.

**Comment by jlmuir** [comment]
On 09/21, Ivars Karpics wrote:

> However, it will not possible to test all hardware objects because there are some Qt dependecies within them (you can not use Qt objects without creating QApplication). For example, Qt4_LimaVideo is used by Qt4_GraphicsManager, that is part of BeamlineSetup, AbstractCollect, etc.

Hi, Ivars!

I see.  Well, it might be a lot of work (I don't know without looking at it), but sometimes there are ways around the kind of issue you describe.  For example, instead of passing in a Qt4_LimaVideo instance, you could pass in another object that holds either an instance of Qt4_LimaVideo or a special test instance.  This object defines a new interface that is not tied to Qt.  For normal use, the object just delegates to the Qt4_LimaVideo instance, but for testing, it would delegate to the special test instance.  This is the Bridge design pattern.

If the above won't work because Qt4_GraphicsManager creates its own instance of Qt4_LimaVideo and it can't be changed to accept an instance, you can use the Registry design pattern where a registry object holds a reference to the correct object.  Then, instead of Qt4_GraphicsManager instantiating a Qt4_LimaVideo, it would ask the registry object for an instance.  The registry object would be preconfigured to vend objects appropriate for production or objects appropriate for testing.

There are lots of variations on this too, depending on the situation, but they essentially amount to changing the code so that it's testable.  For example, if Qt4_LimaVideo is an interface, then it's even easier to deal with since you can create a special test implementation of that interface and pass an instance of that around in place of the real Qt4_LimaVideo implementation instance.

Here's an article that discusses some of the testing approaches:

  http://martinfowler.com/articles/mocksArentStubs.html

> On the last PR #137  it tried to offer two solutions:
> 1. A jupyter notebook loads example hardware repository. You can load any hardware object, see methods, variables, etc. This could be useful to learn better the HardwareRepository

Interesting.

> 1. A mxcube_unittest.py with some tests. Here we could put all tests cases to test mxcube. For example, now it checks some get\* methods.

Nice.

> Maybe this helps to start rolling this testing question.

Could be.  Thanks!  I consider this question to be answered, so I'm happy for it to be closed.

**Comment by IvarsKarpics** [comment]
Hi,
In principle It is possible to create mockup graphics manager to make BeamlineSetup and other hardware objects working also without Qt application.
I will close this particular issue, but at any moment we can return to this question. I can imagine even a mini session about testing and performance during the next mxcube meeting.
