### ISSUE TITLE
Quitting MXCuBE modifies example_mxcube_qt4.gui

### ISSUE THREAD

**Issue by jlmuir** [mxcube/mxcubeqt#154]
I start with no changes in my repo:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

Then I start MXCuBE (using `bin/mxcube`).  My repo is still clean as above.

But then after I quit MXCuBE, my repo is not clean:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   example_mxcube_qt4.gui

no changes added to commit (use "git add" and/or "git commit -a")
```

The diff is not too useful because the file is just one super long line:

```
$ git diff
diff --git a/example_mxcube_qt4.gui b/example_mxcube_qt4.gui
index cdb6432..35acd98 100644
--- a/example_mxcube_qt4.gui
+++ b/example_mxcube_qt4.gui
@@ -1 +1 @@
-[{'signals': {'isShown': (), 'enableExpertMode': (), 'isHidden': (), 'quit': ()}, 'conne
\ No newline at end of file
+[{'signals': {'isShown': (), 'enableExpertMode': (), 'isHidden': (), 'quit': ()}, 'conne
\ No newline at end of file
```

This is with the master branch.  I would expect running MXCuBE to not modify any files in the repo.

**Comment by IvarsKarpics** [comment]
Hi @jlmuir ,

If the user who runs mxcube can modify the gui file then after quitting mxcube, the window size and position is saved. I will check if there is a way to disable this feature. Other issue is the hard readable gui file. For this there is an another issue in BlissFramework mxcube/BlissFramework#9

**Comment by mguijarr** [comment]
As @IvarsKarpics already pointed out, the file modification is a feature. 

I understand it is a problem when testing like you were doing, though. Normally, `example_mxcube_qt4.gui` is just an example file ; it should be copied to `mxcube.gui` before running for the first time, so it goes out of git hands.

An easy fix could be to modify `bin/mxcube` to not use `example_mxcube_qt4.gui`. Instead, if `mxcube.gui` does not exist it could prompt the user to create it from `example_mxcube_qt4.gui`.

What do you think ?

**Comment by jlmuir** [comment]
Well, I'll just say what I would wish for, but it could be that it's not a standard thing to do with Qt or I'm not understanding what the `mxcube.gui` (or `example_mxcube_qt4.gui`) file is.

If I were to deploy MXCuBE in a production environment, where would the `mxcube.gui` file go?  Would I be able to install it in a read-only location?  For example, on a Unix-like OS, application files are typically installed under `/usr` (or, for local things, `/usr/local` or `/opt`), and these files would normally be owned by root and read-only to a regular user.  So to me, I would expect that MXCuBE never tries to write to the `mxcube.gui` file that is part of the installed application.

I would expect that if MXCuBE wants to save some information about the last state of its window (e.g., position and size), it should do that in a standard location for this kind of thing for the current user.  On a Unix-like OS, this might be something like `~/.mxcube/mxcube.gui` or `~/.mxcube/state/mxcube.gui`.  Or, if using the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), it might be `~/.cache/mxcube/mxcube.gui`.  And it might make sense to store *only* the position and size (e.g., `~/.mxcube/state/position` and `~/.mxcube/state/size`) rather than a complete dump of whatever the `mxcube.gui` file contains.  And of course, these locations would be different on Windows and macOS.

**Comment by IvarsKarpics** [comment]
At our beamlines we do exactly what you mentioned. In the production all mxcube files are under `/opt` and belongs to one specific user. In our case it is not root, lets call it `beamline_admin`). All users run mxcube under their accounts and have just read access to the file. So the gui file after closing mxcube is not rewritten. However, when I have to do changes in the gui (remove bricks, change some properties) I log as `beamline_admin` and save the gui file.
I am not sure if it is easy to implement a save for each user.
For the testing and developing purposes I would always keep a copy of gui file and when something goes wrong then just restore it. Or use `git checkout -- example_mxcube_qt4.gui` to restore the file

**Comment by mguijarr** [comment]
The `mxcube.gui` file contains the layout, the widgets (aka bricks), the connections between bricks, and the properties for each component. As it contains the layout, it also contains default sizes for the windows and this is mainly what is saved when mxcube quits.

@jlmuir It was a kind of bad design decision to use the same file for parameters that change according to user preferences and for the whole application description. We have this because MXCuBE still relies on
the BlissFramework, an ancient framework (14 years ago) originally developed by me for internal use at ESRF (by the way, if I would do it today it would be very different ! Lessons learned...).

The `. gui` file is created by the GUI editor that comes with the BlissFramework. You can see it by doing `mxcube -d`. Normally there is a `startGUI` script to be able to create new BlissFramework user interfaces. If you are curious maybe you already tried.
In the past, many graphical applications have been built with the BlissFramework at ESRF, for different beamlines.

As you know we are actively working on MXCuBE 3, which is a web application. All ESRF development effort goes to this new version. So unfortunately from my side there won't be any change regarding the BlissFramework code.

Hopefully we can still find a simple solution for the issue you raised, not involving too much coding.

**Comment by mguijarr** [comment]
Solved by Ivars' fix (merged)
