### ISSUE TITLE
Hackathon @ Soleil

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/mxcubeqt#172]
Has anyone an idea about the issues of the hackathon at Soleil?

**Comment by MartinSavko** [comment]
Hi Jordi,

this is my general idea: we should focus on small number of project(s)
where we could see fruits of the effort by the end of the day.

Each proposed project should have at least one stakeholder -- a person that
feels passionately about the problem and either wants to educate the rest
of us or ask for help in the struggle of implementing new functionality or
refactoring of the code.

Everyone that has an idea is invited to propose a project (either
successful or not successful or just hopeful). Then we will assign order to
projects or topics by a poll and go through them in order of preference
during the hackaton.

Although it is inherently difficult we should strive to combat the
confirmation bias -- e.g. try to talk about what does not work not only
about what does.

The project I have been working on recently and would like to propose:
"System for automatic sample recognition in cryogenic dewars and its
integration in MXCuBE" (I will give a talk during one of the general
sessions, we could work on making the code general to make it iuseful for
everyone).

I have about four things that I can not make to work and will propose one
of them later :)

Cheers,
Martin

**Comment by rhfogh** [comment]
Dear All,


I do not know if it is the kind of thing you want to talk about, but I 
have found it  quite complicated to get to the point where I could set 
up a functioning version of MXCuBE on a development machine, be it the 
Qt3, the Qt4, or the web version. And for that matter to get a handle on 
how things work, internally. Would it make sense to have a quick session 
about where the documentation is (if it is) or what the precise 
installation requirements are? It would be good if the next person who 
joins the collaboration had an easier time of it than I have had ;-).


Yours,


Rasmus

**Comment by MartinSavko** [comment]
Hi Rasmus,

Thank you for the suggestion. I think it is a very good topic.

Cheers,
Martin

**Comment by IvarsKarpics** [comment]
Hi all,

I do not mind to show how to setup mxcube with Qt4. I think its worth repeat it for people who are new in MXCuBE. So I could propose two ideas, sessions:
1. Setting up MXCuBE Qtx (a virtual machine with clean linux is necessary).
2. Developing new graphical object in MXCuBE Qtx (a running MXCuBE Qtx version is necessary).

Cheers,
Ivars

**Comment by hnaalas** [comment]
I'd love it! Sounds like a very good idea indeed.

leo

-
Leonard Chavas
- 
Synchrotron SOLEIL
Proxima-I
L'Orme des Merisiers
Saint-Aubin - BP 48
91192 Gif-sur-Yvette Cedex
France
- 
Phone:  +33 169 359 746
Mobile: +33 644 321 614
E-mail: leonard.chavas@synchrotron-soleil.fr
-

**Comment by rhfogh** [comment]
Dear All,


That sounds great!


I hope that under installing you will give a brief mention of scipy 
(which is incompatible with up-to-date numpy) and matplotlib (which 
seems to be particularly finicky with respect to dependencies).


Yours,


Rasmus

**Comment by mguijarr** [comment]
Hi all :)

I think it would be great to provide Dockerfiles to be able to run MXCuBE within a Docker container, for testing and small developments purpose.

The added benefit of publishing the Dockerfile (and not directly the image) is that it shows the "recipe" to install MXCuBE - I like when things are self-documenting.

So I created this new repository: https://github.com/mxcube/mx3docker

At the moment, the Dockerfile is for installing MXCuBE 2.2/Qt 3, very similar version to what we are running at ESRF. It is based on the venerable Debian 6 distribution... This is still what we have in our beamline computers ;) Not for long hopefully, but...

It would be great to have a Dockerfile for MXCuBE 2.2/Qt 4, and the master version of course.

@jordiandreu: I was working on Docker for Qt4 version. Is anyone else working on this?

@meguiraun: Antonio made a Docker image for MXCuBE 3... Might be good to publish the Dockerfile in this repository too.

---

Regarding the hackathon, I would prefer not to spend time installing if we can use Docker images instead.
Maybe we can explain how to use Docker (even if personally I am far from being proficient with Docker !).

I would prefer if we concentrate on improving mockups and abstract classes. Making new UI components is of course a good idea too, but I am bit worried if everybody starts to make his own widgets: one of the big strengths of MXCuBE is the common user interface, it would be more fruitful to concentrate on the back-end (Hardware Objects) in my opinion.

Moreover, MXCuBE 3 is coming and Qt widgets cannot be reused. So new components means we have to provide also an equivalent web version of those, which is duplicating the work somehow.

**Comment by MartinSavko** [comment]
Hi Matias, all,

the docker option sounds very good and it would be great to have images ready before the hackaton.

I list here the topics that have been proposed so far with a name of a person(s) that could lead the charge in each case. I would like to propose one more that has not been mentioned yet for MXCuBETestEnvironment.py introduction by Vicente -- a module allowing testing and development of individual Bricks and HardwareObjects without a need to launch entire application.

1. Setting up MXCuBE 
    a) problems (Rasmus)
    b) Qt4 (Ivars)
    c) Web (?)
    c) Docker (Matias)
2. Developing new graphical object in MXCuBE Qt (Ivars)
3. Improving mockups and abstract classes (Matias) 
4. MXCuBETestEnvironment.py introduction (Vicente)
5. Extending sample changer object by adding sample recognition ability (Martin) 

I feel the point 3 on mockups and abstract classes is important but also much too general. It would be probably useful if we concentrated on a few concrete examples e.g. a motor, an experimental method to better understand what are the current limitations and how to improve. 

Regarding the topic 2 (new graphical object in Qt) and the transition to MXCuBE 3 it would be very interesting to actually compare how different the approach to development of new graphical elements with those two technologies is for the objects of comparable functionality.

Please do not hesitate to correct my synthesis and propose more topics.

Cheers,
Martin

**Comment by marcus-oscarsson** [comment]
Dear all,

We have been discussing abstractions and mockup objects for quite a while and I think its essential that we actually get it done. The ambition is clearly there in version 2.2 of hardware objects and a lot of good work have already be done but I think we are far from finished. The interface of each object should probably be discussed and decided upon in a suitable forum, either through PRs or more formal means (like during a developers meeting:) ). I'm sure more discussions and also maybe a bit of patience is needed to complete this task since we are quite a lot of people involved. However id really love to see more implementation effort (maybe during a hackathon) go into improving the core of MXCuBE, especially the hardware objects.

As the project grows and more partners joins it gets even more important to improve the abstractions and the overall architecture. Something that will make it easier to adapt, contribute to and finally also maintain the project.

Cheers,
Marcus

**Comment by mguijarr** [comment]
Hi @MartinSavko (and others !),

I agree mockups and abstract classes is a broad topic, that is not suitable for a hackathon where people are supposed to code/explore something together. As you say, it's better to concentrate on concrete
cases.

Some topics are more for the developers meeting. Do you already know what to discuss during the
developers meeting ?

Due to travel constraints, some people may not be able to attend the hackathon or may leave
earlier - maybe a good idea is to mix the two events: only one 'Developers session' with both
meeting and hackathon so we can start one day before.

Regarding web UI components: we can take an example (like, motor control...) to show how to build new UI elements for MXCuBE 3, but in fact we already had this kind of presentation (by F. Bolmsten) during our meeting at Hamburg.
But there is something else... The MXCuBE 3 UI is *a lot* different from MXCuBE 2, in many aspects - in the general case people cannot just make a new Qt widget and convert it to a web component because the UI is completely different. I would say, once the majority switch to MXCuBE 3 we can think of improving the UI, and then changing/adding components. We are not there yet, so a course on writing components for MXCuBE 3 is maybe a bit premature.

In my opinion it's better not to add UI components to MXCuBE at all at the moment, because it broadening the gap between MXCuBE 2 and MXCuBE 3. I advocate for a "UI freeze" until MXCuBE 3 adoption.

**Comment by IvarsKarpics** [comment]
Hi @mguijarr  and others,

I would suggest to set priorities for the hackathon, because there will be people who attend also ispyb meeting (like me) or not able to come one day before (also like me). The most important would be to sync master with 2.1 and 2.2. As we saw from the google docs there is a forest of different versions/branches deployed at the beamlines. At some point a productive discussion will stop because the versions (list of features) will differ significantly and will not be compatible. We could do a live rebasing and have an open discussion/coding. Lets say we devote one afternoon to produce a synchronized set of most important hardware objects:
- queue_entry
- queue_model_objects
- AbstractCollect, AbstractMulticollect
- QueueModel, QueueManager
- If we have enough time we could touch AbstractMotor, AbstractDetector, ...

Other topics, listed by @MartinSavko  are of course also relevant, but they do not necessary require all developers in one room. I am fine to show how to set up mxcube (we can modify https://github.com/mxcube/mxcube/blob/master/docs/source/installation_instructions_qt4.rst if necessary) or during show a break how to create a qt widget (we did that at the meeting in Hamburg: https://github.com/mxcube/mxcube/wiki/How-to-create-a-hardware-object-and-brick-in-Qt4)

Cheers,
Ivars

**Comment by marcus-oscarsson** [comment]
Hi all,

I will not attend to the last day of the meeting, so I will probably miss the bigger part of hackathon. I agree with Ivars that its important to sync master with 2.1 and 2.2 in the sense that the result would be a version, 2.3, with clearly defined abstract classes and more complete mockup objects. In my opinion finishing what was meant to be version 2.2. We should also take a look at the overall architecture (mostly data model and queue related, perhaps also collect ?), the API would preferably also be harmonized so that we are using the same conventions between abstract classes. I also think we should start to use semantic versioning or similar for 2.3, as discussed on the previous meeting. I personally don't think its a good idea to use master for other means than development.

I think basically all hardware objects should be reviewed, looking at the list of hardware objects that Ivars made in the previous message. The ones that have to do with the queue are indeed important and should be reviewed and maybe re designed at some point, however I think we should focus on finishing the essential abstraction work. So I would rather see things like Energy, Resolution, Detector, Collect, MultiColllect and maybe even basic translational motors like Beamstop, and Shutters.

Cheers,
Marcus

**Comment by jordiandreu** [comment]
I was working on Docker for Qt4 version. Is anyone else working on this?

**Comment by IvarsKarpics** [comment]
Hi @jordiandreu ,

No, personally I did not start to create a docker container. So, I encourage you to continue!
