### ISSUE TITLE
Renaming the repository

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubeqt#278]
Hi all,

I would propose to rename the repository to something like mxcube_qt or mxcube_desktop, because mxcube/mxcube do not say a lot. What do you think?

**Comment by rhfogh** [comment]
Sounds reasonable. Should mxcube3 be renamed mxcube_web then?

**Comment by marcus-oscarsson** [comment]
We would like to keep mxcube3 as it is the established name for the project.

I'm not so sure about mxcube_desktop, mxcube_qt could possible work if you think that is better. How about mxcube2 ? It would be more in line with the versioning scheme and project history.

Marcus

**Comment by beteva** [comment]
Agree with @marcus-oscarsson.

**Comment by rhfogh** [comment]
I will not argue against keeping mxcube3 as a name. But I think it is a bit confusing to have version 3.0 of 'mxcube2'. Also it does sort of imply that mxcube2 is an old version that will be replaced by mxcube3. Would you be OK with that, Ivars?

**Comment by IvarsKarpics** [comment]
Looking at numbers naturally one thinks that 3 is next after 2 :) , but maybe in the software world is not like that: for example Epics versioning, where 3 and 4 is different versions and latest 7 is like a merge of 3 and 4.
Generally project/software name do not include versioning number and I would suggest to postpone this question till the next face to face meeting.

**Comment by marcus-oscarsson** [comment]
I agree that it in general is a bad idea to include the version number in the project name, I'm for the same reason not sure including what tech is used is much better. I can definitely understand that the naming is confusing from an external perspective, I don't think its particularly good my self.

The name MXCuBE3 was chosen for the project from the start and has been used since in various contexts so it will for natural reasons remain like this. So we would of course like to keep the name mxcube3 for the repository as well, to at least keep the confusion to a minimal.

mxcube_qt is in my opinion a better name than mxcube_desktop, since the later does not really tell us what it is.

Marcus

**Comment by jordiandreu** [comment]
After today's discussion in the meeting about the renaming of the HardwareRepository repository, I would understand to use the same approach for the mxcube/mxcube renaming.

I'm also in favour to not add the version number to the project name. For me it looks more natural to include a reference to the technology/framework used, also taking into account the two different approaches already available in the project: web and Qt. For this, it sounds reasonable to me use the suffix -qt/Qt rather than desktop.

Also add that, when communicating to the MX community, it is important to have a clear naming convention to make the people identify each front-end version of the project (web and qt) as well as the backend (HardwareRepository).

Nevertheless, I'm not saying the current web version name has to be changed, I understand the reasons @marcus-oscarsson 
 commented, but maybe I would have chosen a different name.

**Comment by marcus-oscarsson** [comment]
@jordiandreu I agree in principle to what you mention above. In addition to what I also said earlier I can also mention that the name was chosen very early and not by myself. I would be happy to change the name to something more appropriate but it has to be seen with the others as well. Everything has its time and moment so we can maybe take a closer look at changing the name of Qt and web projects once its done for HWR. Still keeping in mind that we need to find a way/name that can be consistently be applied to each subproject.

**Comment by IvarsKarpics** [comment]
Project was renamed to mxcubeqt
