### ISSUE TITLE
How to import

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubeqt#297]
The particular structure where HardwareRepository is both on the PYTHONPATH and inside the top directory (which is also on the PYTHONPATH) makes it ambiguous how you should import things. The possibility of relative imports (which are handled differently in Python 2 and Python 3 BTW) adds extra ambiguity. Could we agree on a standard way of importing things?

- This is not just nitpicking - if you use two different import statements, you can import the same package twice. That means that checking for e.g. you might get
HardwareRepository.HardwareObjects.queue_model_enumerables.States.OPEN is queue_model_enumerables.States.OPEN
to evaluate to False, since this is not the same enum class in the two cases.

- The trigger for this Issue are two imports in PR #296 

In BlissFramework/Bricks/Qt4_SampleChangerBrick3.py:
from HardwareRepository.HardwareObjects import SC3

In BlissFramework/Bricks/Qt4_sample_changer_helper.py:
abstract.AbstractSampleChanger import SampleChangerState, SampleChangerMode, SampleChanger

Both are correct, but would consitency not be better?

**Comment by marcus-oscarsson** [comment]
Yes I agree, this is actually not very good. It would be good if we could remove this ambiguity created by explicitly adding paths to the PYTHONPATH. It would also be good if we could use absolute imports to avoid confusion and to be Python 3 compatible and maybe use `from __future__ import absolute_import`

In your first point, when the module loads twice, is it because of a relative import ?. It seems like the later statement queue_model_enumerables.States.OPEN is due to a relative import, could you give me the exact import statements used ?

**Comment by rhfogh** [comment]
@marcus-oscarsson 
It is a while ago, and I changed the import statements then. I shall see what I can dig up

**Comment by jordiandreu** [comment]
I find some Pros and Cons here about the import statements:

https://realpython.com/absolute-vs-relative-python-imports/

I would be in favor of absolute imports. In this case, the PR #296 should adopt this convention.

**Comment by IvarsKarpics** [comment]
Hi all,

My latest PR #295  actually contains both import styles (in fact that SC3 import should not be there). I would also prefer an absolute import, but it might be that the import statement is a bit long.
