### ISSUE TITLE
Make centred point markers to the size/shape of the beam

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcubeqt#55]

**Comment by IvarsKarpics** [comment]
Not sure if this is still an issue. If the marker is to big then it could be a problem to select one if several markers overlap.

**Comment by IvarsKarpics** [comment]
I will close this issue, because it is not actual right now. There is no brick to define beam size for each collection, no variables in data model and no implementation in ShapeHistory. Also to large beam size could confuse and selecting point could be problematic. If there is a wish we can return to this question.
